### ISSUE TITLE
Exceptions raised in chocolateyInstall.ps1 are not resulting in a non-zero exit codes returned from chocolatey

### ISSUE THREAD

**Issue by mwrock** [chocolatey/chocolatey#659] opened 2015-01-12 03:34 UTC
Exceptions raised in chocolateyInstall.ps1 are not resulting in a non-zero exit code because it is writing to the $chocolateyErrored variable in a different scope from where it was created.

**Comment by mwrock** [comment] 2015-01-12 03:35
PR #658 should fix this.

**Comment by ferventcoder** [comment] 2015-01-28 04:03
Duplicate of #568

**Closed** 2015-01-28 04:03 UTC
Labels: v0.9.8.32
