### ISSUE TITLE
Download directory should be configurable (don't assume $env:TEMP is predefined)

### ISSUE THREAD

**Issue by ilinkuo** [chocolatey/chocolatey#307] opened 2013-06-28 17:03 UTC
I want to use Chocolatey in a restricted corporate environment where we'are only able to run things if they are installed into a specific directory. I can get Chocolatey itself to install to that directory via the ChocolateyInstall environment variable according to the instructions at https://github.com/chocolatey/chocolatey/wiki/Installation. However, when chocolatey tries to install apps, it downloads the installer exe to the default download location -- c:\Users\MyUSERId\APPDATA\LOCAL\TEMP\CHOCOLATEY\... and tries to run the .exe from there. This is not allowed. It needs to be run in a subdirectory of ChocolateyInstall, preferably %ChocolateyInstall%\temp

**Comment by ferventcoder** [comment] 2015-01-02 18:39
Closed #647 as a duplicate of this one.

**Closed** 2015-01-02 20:39 UTC
Labels: 3 - Done, v0.9.8.29
