### ISSUE TITLE
ERROR: Exception calling "Start" with "0" argument(s)

### ISSUE THREAD

**Issue by CWempe** [chocolatey/chocolatey#724] opened 2016-09-24 12:15 UTC
I did a fresh Windows 10 x64 install yesterday and tried to install a bunch of programms via chocolately.

Butr some packages failed, because of this error.

```
ERROR: Exception calling "Start" with "0" argument(s): "Der Verzeichnisname ist ungültig"
The install of musicbee was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\musicbee\tools\chocolateyInstall.ps1'.
 See log for details.
```

```
2016-09-24 14:05:13,627 [DEBUG] - Configured chocolatey.infrastructure.logging.log4net.config.xml from assembly choco, Version=0.10.1.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb
2016-09-24 14:05:13,627 [DEBUG] - Configured chocolatey.infrastructure.logging.log4net.config.xml from assembly choco, Version=0.10.1.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb
2016-09-24 14:05:13,645 [DEBUG] - XmlConfiguration is now operational
2016-09-24 14:05:13,778 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\config\chocolatey.config.update".
2016-09-24 14:05:13,785 [INFO ] - ============================================================
2016-09-24 14:05:13,793 [INFO ] - Chocolatey v0.10.1
2016-09-24 14:05:13,809 [DEBUG] - Chocolatey is running on Windows v 10.0.14393.0
2016-09-24 14:05:13,814 [DEBUG] - Attempting to delete file "C:/ProgramData/chocolatey/choco.exe.old".
2016-09-24 14:05:13,817 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\choco.exe.old".
2016-09-24 14:05:13,827 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" install musicbee -v --allow-empty-checksums -y
2016-09-24 14:05:13,831 [DEBUG] - Received arguments: install musicbee -v --allow-empty-checksums -y
2016-09-24 14:05:13,872 [DEBUG] - RemovePendingPackagesTask is now ready and waiting for PreRunMessage.
2016-09-24 14:05:13,879 [DEBUG] - Sending message 'PreRunMessage' out if there are subscribers...
2016-09-24 14:05:13,888 [DEBUG] - [Pending] Removing all pending packages that should not be considered installed...
2016-09-24 14:05:13,931 [DEBUG] - The source 'https://chocolatey.org/api/v2/' evaluated to a 'normal' source type
2016-09-24 14:05:13,935 [DEBUG] - 
NOTE: Hiding sensitive configuration data! Please double and triple 
 check to be sure no sensitive data is shown, especially if copying 
 output to a gist for review.
2016-09-24 14:05:13,945 [DEBUG] - Configuration: CommandName='install'|
CacheLocation='C:\Users\USER\AppData\Local\Temp\chocolatey'|
ContainsLegacyPackageInstalls='True'|
CommandExecutionTimeoutSeconds='2700'|WebRequestTimeoutSeconds='30'|
Sources='https://chocolatey.org/api/v2/'|SourceType='normal'|
Debug='False'|Verbose='True'|Force='False'|Noop='False'|
HelpRequested='False'|RegularOutput='True'|QuietOutput='False'|
PromptForConfirmation='False'|AcceptLicense='True'|
AllowUnofficialBuild='False'|Input='musicbee'|AllVersions='False'|
SkipPackageInstallProvider='False'|PackageNames='musicbee'|
Prerelease='False'|ForceX86='False'|OverrideArguments='False'|
NotSilent='False'|ApplyPackageParametersToDependencies='False'|
ApplyInstallArgumentsToDependencies='False'|IgnoreDependencies='False'|
AllowMultipleVersions='False'|AllowDowngrade='False'|
ForceDependencies='False'|Information.PlatformType='Windows'|
Information.PlatformVersion='10.0.14393.0'|
Information.PlatformName='Windows'|
Information.ChocolateyVersion='0.10.1.0'|
Information.ChocolateyProductVersion='0.10.1'|
Information.FullName='choco, Version=0.10.1.0, Culture=neutral, PublicKeyToken=79d02ea9cad655eb'|

Information.Is64Bit='True'|Information.IsInteractive='True'|
Information.IsUserAdministrator='True'|
Information.IsProcessElevated='True'|
Information.IsLicensedVersion='False'|Features.AutoUninstaller='True'|
Features.ChecksumFiles='True'|Features.AllowEmptyChecksums='True'|
Features.AllowEmptyChecksumsSecure='True'|
Features.FailOnAutoUninstaller='False'|
Features.FailOnStandardError='False'|Features.UsePowerShellHost='True'|
Features.LogEnvironmentValues='False'|Features.VirusCheck='False'|
Features.FailOnInvalidOrMissingLicense='False'|
Features.IgnoreInvalidOptionsSwitches='True'|
Features.UsePackageExitCodes='True'|
Features.UseFipsCompliantChecksums='False'|
ListCommand.LocalOnly='False'|
ListCommand.IncludeRegistryPrograms='False'|ListCommand.PageSize='25'|
ListCommand.Exact='False'|ListCommand.ByIdOnly='False'|
ListCommand.IdStartsWith='False'|ListCommand.OrderByPopularity='False'|
ListCommand.ApprovedOnly='False'|
ListCommand.DownloadCacheAvailable='False'|
ListCommand.NotBroken='False'|UpgradeCommand.FailOnUnfound='False'|
UpgradeCommand.FailOnNotInstalled='False'|
UpgradeCommand.NotifyOnlyAvailableUpgrades='False'|
NewCommand.AutomaticPackage='False'|
NewCommand.UseOriginalTemplate='False'|SourceCommand.Command='unknown'|
SourceCommand.Priority='0'|FeatureCommand.Command='unknown'|
ConfigCommand.Command='unknown'|PinCommand.Command='unknown'|
2016-09-24 14:05:13,948 [DEBUG] - _ Chocolatey:ChocolateyInstallCommand - Normal Run Mode _
2016-09-24 14:05:13,954 [INFO ] - Installing the following packages:
2016-09-24 14:05:13,961 [INFO ] - musicbee
2016-09-24 14:05:13,968 [INFO ] - By installing you accept licenses for the packages.
2016-09-24 14:05:15,196 [INFO ] - 
musicbee v3.0.5995 [Approved]
2016-09-24 14:05:15,260 [DEBUG] - Setting installer args for musicbee
2016-09-24 14:05:15,264 [DEBUG] - Setting package parameters for musicbee
2016-09-24 14:05:15,267 [DEBUG] - Contents of 'C:\ProgramData\chocolatey\lib\musicbee\tools\chocolateyInstall.ps1':
2016-09-24 14:05:15,275 [DEBUG] - $ErrorActionPreference = 'Stop';
$packageName = "musicbee"
$version = '3.0.5995'
$zipFile = "MusicBeeSetup_3_0_Update1.zip"
$exeFile = "MusicBeeSetup_3_0_Update1.exe"
$url = "http://musicbee.niblseed.com/$zipFile"
$checksum = 'EECD7BB9E6C09AFFEC31B8150B21FD98'
$checksumType  = 'md5'
$silentArgs = "/S"
$validExitCodes = @(0)

try { 
  $chocTempDir = Join-Path $env:TEMP "chocolatey"
  $tempDir = Join-Path $chocTempDir "$packageName"
  if (![System.IO.Directory]::Exists($tempDir)) {[System.IO.Directory]::CreateDirectory($tempDir)}
  $file = Join-Path $tempDir $zipFile
          
  Get-ChocolateyWebFile $packageName $file $url
  Get-ChocolateyUnzip $file $tempDir "" $packageName

  $file = Join-Path $tempDir $exeFile

  Install-ChocolateyInstallPackage $packageName 'exe' $silentArgs $file -validExitCodes $validExitCodes -Checksum "$checksum" -ChecksumType "$checksumType"

} catch {
  throw
}
2016-09-24 14:05:15,299 [DEBUG] - Calling built-in PowerShell host with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\musicbee\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters ''']
2016-09-24 14:05:15,312 [DEBUG] - Redirecting System.Management.Automation.resources, Version=3.0.0.0, Culture=de-DE, PublicKeyToken=31bf3856ad364e35, requested by ''
2016-09-24 14:05:16,686 [DEBUG] - Host version is 5.1.14393.0, PowerShell Version is '5.1.14393.187' and CLR Version is '4.0.30319.42000'.
2016-09-24 14:05:17,005 [DEBUG] - Loading community extensions
2016-09-24 14:05:17,041 [DEBUG] - Importing 'C:\ProgramData\chocolatey\extensions\mm-choco\Get-AppInstallLocation.psm1'
2016-09-24 14:05:17,045 [INFO ] - VERBOSE: Loading module from path 'C:\ProgramData\chocolatey\extensions\mm-choco\Get-AppInstallLocation.psm1'.
2016-09-24 14:05:17,060 [INFO ] - VERBOSE: Exporting function 'Get-AppInstallLocation'.
2016-09-24 14:05:17,085 [INFO ] - VERBOSE: Importing function 'Get-AppInstallLocation'.
2016-09-24 14:05:17,102 [DEBUG] - Importing 'C:\ProgramData\chocolatey\extensions\mm-choco\Register-Application.psm1'
2016-09-24 14:05:17,107 [INFO ] - VERBOSE: Loading module from path 'C:\ProgramData\chocolatey\extensions\mm-choco\Register-Application.psm1'.
2016-09-24 14:05:17,118 [INFO ] - VERBOSE: Exporting function 'Register-Application'.
2016-09-24 14:05:17,127 [INFO ] - VERBOSE: Importing function 'Register-Application'.
2016-09-24 14:05:17,144 [INFO ] - VERBOSE: Exporting function 'Format-FileSize'.
2016-09-24 14:05:17,157 [INFO ] - VERBOSE: Exporting function 'Get-ChecksumValid'.
2016-09-24 14:05:17,168 [INFO ] - VERBOSE: Exporting function 'Get-ChocolateyUnzip'.
2016-09-24 14:05:17,178 [INFO ] - VERBOSE: Exporting function 'Get-ChocolateyWebFile'.
2016-09-24 14:05:17,188 [INFO ] - VERBOSE: Exporting function 'Get-EnvironmentVariable'.
2016-09-24 14:05:17,200 [INFO ] - VERBOSE: Exporting function 'Get-EnvironmentVariableNames'.
2016-09-24 14:05:17,208 [INFO ] - VERBOSE: Exporting function 'Get-FtpFile'.
2016-09-24 14:05:17,218 [INFO ] - VERBOSE: Exporting function 'Get-OSArchitectureWidth'.
2016-09-24 14:05:17,228 [INFO ] - VERBOSE: Exporting function 'Get-ToolsLocation'.
2016-09-24 14:05:17,242 [INFO ] - VERBOSE: Exporting function 'Get-UACEnabled'.
2016-09-24 14:05:17,252 [INFO ] - VERBOSE: Exporting function 'Get-UninstallRegistryKey'.
2016-09-24 14:05:17,265 [INFO ] - VERBOSE: Exporting function 'Get-VirusCheckValid'.
2016-09-24 14:05:17,273 [INFO ] - VERBOSE: Exporting function 'Get-WebFile'.
2016-09-24 14:05:17,283 [INFO ] - VERBOSE: Exporting function 'Get-WebFileName'.
2016-09-24 14:05:17,294 [INFO ] - VERBOSE: Exporting function 'Get-WebHeaders'.
2016-09-24 14:05:17,302 [INFO ] - VERBOSE: Exporting function 'Install-BinFile'.
2016-09-24 14:05:17,313 [INFO ] - VERBOSE: Exporting function 'Install-ChocolateyDesktopLink'.
2016-09-24 14:05:17,324 [INFO ] - VERBOSE: Exporting function 'Install-ChocolateyEnvironmentVariable'.
2016-09-24 14:05:17,334 [INFO ] - VERBOSE: Exporting function 'Install-ChocolateyExplorerMenuItem'.
2016-09-24 14:05:17,344 [INFO ] - VERBOSE: Exporting function 'Install-ChocolateyFileAssociation'.
2016-09-24 14:05:17,355 [INFO ] - VERBOSE: Exporting function 'Install-ChocolateyInstallPackage'.
2016-09-24 14:05:17,366 [INFO ] - VERBOSE: Exporting function 'Install-ChocolateyPackage'.
2016-09-24 14:05:17,375 [INFO ] - VERBOSE: Exporting function 'Install-ChocolateyPath'.
2016-09-24 14:05:17,384 [INFO ] - VERBOSE: Exporting function 'Install-ChocolateyPinnedTaskBarItem'.
2016-09-24 14:05:17,393 [INFO ] - VERBOSE: Exporting function 'Install-ChocolateyPowershellCommand'.
2016-09-24 14:05:17,403 [INFO ] - VERBOSE: Exporting function 'Install-ChocolateyShortcut'.
2016-09-24 14:05:17,415 [INFO ] - VERBOSE: Exporting function 'Install-ChocolateyVsixPackage'.
2016-09-24 14:05:17,425 [INFO ] - VERBOSE: Exporting function 'Install-ChocolateyZipPackage'.
2016-09-24 14:05:17,435 [INFO ] - VERBOSE: Exporting function 'Install-Vsix'.
2016-09-24 14:05:17,445 [INFO ] - VERBOSE: Exporting function 'Set-EnvironmentVariable'.
2016-09-24 14:05:17,456 [INFO ] - VERBOSE: Exporting function 'Set-PowerShellExitCode'.
2016-09-24 14:05:17,467 [INFO ] - VERBOSE: Exporting function 'Start-ChocolateyProcessAsAdmin'.
2016-09-24 14:05:17,477 [INFO ] - VERBOSE: Exporting function 'Test-ProcessAdminRights'.
2016-09-24 14:05:17,486 [INFO ] - VERBOSE: Exporting function 'Uninstall-BinFile'.
2016-09-24 14:05:17,497 [INFO ] - VERBOSE: Exporting function 'Uninstall-ChocolateyEnvironmentVariable'.
2016-09-24 14:05:17,506 [INFO ] - VERBOSE: Exporting function 'Uninstall-ChocolateyPackage'.
2016-09-24 14:05:17,516 [INFO ] - VERBOSE: Exporting function 'Uninstall-ChocolateyZipPackage'.
2016-09-24 14:05:17,527 [INFO ] - VERBOSE: Exporting function 'Update-SessionEnvironment'.
2016-09-24 14:05:17,537 [INFO ] - VERBOSE: Exporting function 'Write-ChocolateyFailure'.
2016-09-24 14:05:17,548 [INFO ] - VERBOSE: Exporting function 'Write-ChocolateySuccess'.
2016-09-24 14:05:17,558 [INFO ] - VERBOSE: Exporting function 'Write-FileUpdateLog'.
2016-09-24 14:05:17,566 [INFO ] - VERBOSE: Exporting function 'Get-AppInstallLocation'.
2016-09-24 14:05:17,575 [INFO ] - VERBOSE: Exporting function 'Register-Application'.
2016-09-24 14:05:17,585 [INFO ] - VERBOSE: Exporting alias 'Get-ProcessorBits'.
2016-09-24 14:05:17,595 [INFO ] - VERBOSE: Exporting alias 'Get-OSBitness'.
2016-09-24 14:05:17,604 [INFO ] - VERBOSE: Exporting alias 'Get-InstallRegistryKey'.
2016-09-24 14:05:17,614 [INFO ] - VERBOSE: Exporting alias 'Generate-BinFile'.
2016-09-24 14:05:17,625 [INFO ] - VERBOSE: Exporting alias 'Add-BinFile'.
2016-09-24 14:05:17,635 [INFO ] - VERBOSE: Exporting alias 'Remove-BinFile'.
2016-09-24 14:05:17,645 [INFO ] - VERBOSE: Exporting alias 'refreshenv'.
2016-09-24 14:05:17,657 [INFO ] - VERBOSE: Importing function 'Format-FileSize'.
2016-09-24 14:05:17,669 [INFO ] - VERBOSE: Importing function 'Get-AppInstallLocation'.
2016-09-24 14:05:17,680 [INFO ] - VERBOSE: Importing function 'Get-ChecksumValid'.
2016-09-24 14:05:17,690 [INFO ] - VERBOSE: Importing function 'Get-ChocolateyUnzip'.
2016-09-24 14:05:17,699 [INFO ] - VERBOSE: Importing function 'Get-ChocolateyWebFile'.
2016-09-24 14:05:17,708 [INFO ] - VERBOSE: Importing function 'Get-EnvironmentVariable'.
2016-09-24 14:05:17,717 [INFO ] - VERBOSE: Importing function 'Get-EnvironmentVariableNames'.
2016-09-24 14:05:17,726 [INFO ] - VERBOSE: Importing function 'Get-FtpFile'.
2016-09-24 14:05:17,737 [INFO ] - VERBOSE: Importing function 'Get-OSArchitectureWidth'.
2016-09-24 14:05:17,749 [INFO ] - VERBOSE: Importing function 'Get-ToolsLocation'.
2016-09-24 14:05:17,759 [INFO ] - VERBOSE: Importing function 'Get-UACEnabled'.
2016-09-24 14:05:17,769 [INFO ] - VERBOSE: Importing function 'Get-UninstallRegistryKey'.
2016-09-24 14:05:17,781 [INFO ] - VERBOSE: Importing function 'Get-VirusCheckValid'.
2016-09-24 14:05:17,788 [INFO ] - VERBOSE: Importing function 'Get-WebFile'.
2016-09-24 14:05:17,799 [INFO ] - VERBOSE: Importing function 'Get-WebFileName'.
2016-09-24 14:05:17,808 [INFO ] - VERBOSE: Importing function 'Get-WebHeaders'.
2016-09-24 14:05:17,817 [INFO ] - VERBOSE: Importing function 'Install-BinFile'.
2016-09-24 14:05:17,827 [INFO ] - VERBOSE: Importing function 'Install-ChocolateyDesktopLink'.
2016-09-24 14:05:17,835 [INFO ] - VERBOSE: Importing function 'Install-ChocolateyEnvironmentVariable'.
2016-09-24 14:05:17,844 [INFO ] - VERBOSE: Importing function 'Install-ChocolateyExplorerMenuItem'.
2016-09-24 14:05:17,854 [INFO ] - VERBOSE: Importing function 'Install-ChocolateyFileAssociation'.
2016-09-24 14:05:17,864 [INFO ] - VERBOSE: Importing function 'Install-ChocolateyInstallPackage'.
2016-09-24 14:05:17,874 [INFO ] - VERBOSE: Importing function 'Install-ChocolateyPackage'.
2016-09-24 14:05:17,884 [INFO ] - VERBOSE: Importing function 'Install-ChocolateyPath'.
2016-09-24 14:05:17,893 [INFO ] - VERBOSE: Importing function 'Install-ChocolateyPinnedTaskBarItem'.
2016-09-24 14:05:17,903 [INFO ] - VERBOSE: Importing function 'Install-ChocolateyPowershellCommand'.
2016-09-24 14:05:17,912 [INFO ] - VERBOSE: Importing function 'Install-ChocolateyShortcut'.
2016-09-24 14:05:17,923 [INFO ] - VERBOSE: Importing function 'Install-ChocolateyVsixPackage'.
2016-09-24 14:05:17,933 [INFO ] - VERBOSE: Importing function 'Install-ChocolateyZipPackage'.
2016-09-24 14:05:17,943 [INFO ] - VERBOSE: Importing function 'Install-Vsix'.
2016-09-24 14:05:17,952 [INFO ] - VERBOSE: Importing function 'Register-Application'.
2016-09-24 14:05:17,960 [INFO ] - VERBOSE: Importing function 'Set-EnvironmentVariable'.
2016-09-24 14:05:17,969 [INFO ] - VERBOSE: Importing function 'Set-PowerShellExitCode'.
2016-09-24 14:05:17,978 [INFO ] - VERBOSE: Importing function 'Start-ChocolateyProcessAsAdmin'.
2016-09-24 14:05:17,987 [INFO ] - VERBOSE: Importing function 'Test-ProcessAdminRights'.
2016-09-24 14:05:17,997 [INFO ] - VERBOSE: Importing function 'Uninstall-BinFile'.
2016-09-24 14:05:18,009 [INFO ] - VERBOSE: Importing function 'Uninstall-ChocolateyEnvironmentVariable'.
2016-09-24 14:05:18,019 [INFO ] - VERBOSE: Importing function 'Uninstall-ChocolateyPackage'.
2016-09-24 14:05:18,029 [INFO ] - VERBOSE: Importing function 'Uninstall-ChocolateyZipPackage'.
2016-09-24 14:05:18,040 [INFO ] - VERBOSE: Importing function 'Update-SessionEnvironment'.
2016-09-24 14:05:18,053 [INFO ] - VERBOSE: Importing function 'Write-ChocolateyFailure'.
2016-09-24 14:05:18,063 [INFO ] - VERBOSE: Importing function 'Write-ChocolateySuccess'.
2016-09-24 14:05:18,071 [INFO ] - VERBOSE: Importing function 'Write-FileUpdateLog'.
2016-09-24 14:05:18,080 [INFO ] - VERBOSE: Importing alias 'Add-BinFile'.
2016-09-24 14:05:18,089 [INFO ] - VERBOSE: Importing alias 'Generate-BinFile'.
2016-09-24 14:05:18,099 [INFO ] - VERBOSE: Importing alias 'Get-InstallRegistryKey'.
2016-09-24 14:05:18,110 [INFO ] - VERBOSE: Importing alias 'Get-OSBitness'.
2016-09-24 14:05:18,119 [INFO ] - VERBOSE: Importing alias 'Get-ProcessorBits'.
2016-09-24 14:05:18,129 [INFO ] - VERBOSE: Importing alias 'refreshenv'.
2016-09-24 14:05:18,140 [INFO ] - VERBOSE: Importing alias 'Remove-BinFile'.
2016-09-24 14:05:18,191 [DEBUG] - Running 'ChocolateyScriptRunner' for musicbee v3.0.5995 with packageScript 'C:\ProgramData\chocolatey\lib\musicbee\tools\chocolateyInstall.ps1', packageFolder:'C:\ProgramData\chocolatey\lib\musicbee', installArguments: '', packageParameters: '',
2016-09-24 14:05:18,200 [DEBUG] - Running 'C:\ProgramData\chocolatey\lib\musicbee\tools\chocolateyInstall.ps1'
2016-09-24 14:05:18,263 [DEBUG] - Running 'Get-ChocolateyWebFile' for musicbee with url:'http://musicbee.niblseed.com/MusicBeeSetup_3_0_Update1.zip', fileFullPath:'C:\Users\USER\AppData\Local\Temp\chocolatey\chocolatey\musicbee\MusicBeeSetup_3_0_Update1.zip', url64bit:'', checksum: '', checksumType: '', checksum64: '', checksumType64: ''
2016-09-24 14:05:18,272 [DEBUG] - Running 'Get-OSArchitectureWidth'
2016-09-24 14:05:18,285 [DEBUG] - CPU is 64 bit
2016-09-24 14:05:18,316 [DEBUG] - Running 'Get-WebHeaders' with url:'https://musicbee.niblseed.com/MusicBeeSetup_3_0_Update1.zip', userAgent: 'chocolatey command line'
2016-09-24 14:05:18,349 [DEBUG] - Setting the UserAgent to 'chocolatey command line'
2016-09-24 14:05:18,353 [DEBUG] - Request Headers:
2016-09-24 14:05:18,369 [DEBUG] -   'Accept':'*/*'
2016-09-24 14:05:18,373 [DEBUG] -   'User-Agent':'chocolatey command line'
2016-09-24 14:05:20,789 [DEBUG] - Url does not have HTTPS available
2016-09-24 14:05:20,799 [DEBUG] - Running 'Get-WebHeaders' with url:'http://musicbee.niblseed.com/MusicBeeSetup_3_0_Update1.zip', userAgent: 'chocolatey command line'
2016-09-24 14:05:20,803 [DEBUG] - Setting the UserAgent to 'chocolatey command line'
2016-09-24 14:05:20,806 [DEBUG] - Request Headers:
2016-09-24 14:05:20,809 [DEBUG] -   'Accept':'*/*'
2016-09-24 14:05:20,813 [DEBUG] -   'User-Agent':'chocolatey command line'
2016-09-24 14:05:21,042 [DEBUG] - Response Headers:
2016-09-24 14:05:21,058 [DEBUG] -   'Keep-Alive':'timeout=5, max=100'
2016-09-24 14:05:21,068 [DEBUG] -   'Connection':'Keep-Alive'
2016-09-24 14:05:21,077 [DEBUG] -   'Accept-Ranges':'bytes'
2016-09-24 14:05:21,084 [DEBUG] -   'Content-Length':'11635249'
2016-09-24 14:05:21,089 [DEBUG] -   'Content-Type':'application/zip'
2016-09-24 14:05:21,094 [DEBUG] -   'Date':'Sat, 24 Sep 2016 12:05:21 GMT'
2016-09-24 14:05:21,098 [DEBUG] -   'ETag':'"b18a31-53429f395d1b6"'
2016-09-24 14:05:21,103 [DEBUG] -   'Last-Modified':'Tue, 31 May 2016 21:21:08 GMT'
2016-09-24 14:05:21,108 [DEBUG] -   'Server':'Apache/2.4.10 (Debian)'
2016-09-24 14:05:21,141 [DEBUG] - musicbee's requested file has already been downloaded. Using cached copy at
 'C:\Users\USER\AppData\Local\Temp\chocolatey\chocolatey\musicbee\MusicBeeSetup_3_0_Update1.zip'.
2016-09-24 14:05:23,171 [DEBUG] - No runtime virus checking built into FOSS Chocolatey. Check out Pro/Business - https://chocolatey.org/compare
2016-09-24 14:05:23,181 [DEBUG] - Checking that 'C:\Users\USER\AppData\Local\Temp\chocolatey\chocolatey\musicbee\MusicBeeSetup_3_0_Update1.zip' is the size we expect it to be.
2016-09-24 14:05:23,192 [DEBUG] - Verifying package provided checksum of '' for 'C:\Users\USER\AppData\Local\Temp\chocolatey\chocolatey\musicbee\MusicBeeSetup_3_0_Update1.zip'.
2016-09-24 14:05:23,212 [DEBUG] - Running 'Get-ChecksumValid' with file:'C:\Users\USER\AppData\Local\Temp\chocolatey\chocolatey\musicbee\MusicBeeSetup_3_0_Update1.zip', checksum: '', checksumType: '', originalUrl: 'http://musicbee.niblseed.com/MusicBeeSetup_3_0_Update1.zip'
2016-09-24 14:05:23,217 [DEBUG] - Empty checksums are allowed due to allowEmptyChecksums feature or option.
2016-09-24 14:05:23,226 [INFO ] - C:\Users\USER\AppData\Local\Temp\chocolatey\chocolatey\musicbee\MusicBeeSetup_3_0_Update1.zip
2016-09-24 14:05:23,268 [DEBUG] - Running 'Get-ChocolateyUnzip' with fileFullPath:'C:\Users\USER\AppData\Local\Temp\chocolatey\chocolatey\musicbee\MusicBeeSetup_3_0_Update1.zip'', destination: 'C:\Users\USER\AppData\Local\Temp\chocolatey\chocolatey\musicbee', specificFolder: '`, packageName: 'musicbee'
2016-09-24 14:05:23,287 [INFO ] - Extracting C:\Users\USER\AppData\Local\Temp\chocolatey\chocolatey\musicbee\MusicBeeSetup_3_0_Update1.zip to C:\Users\USER\AppData\Local\Temp\chocolatey\chocolatey\musicbee...
2016-09-24 14:05:23,299 [DEBUG] - 7zip found at 'C:\ProgramData\chocolatey\tools\7z.exe'
2016-09-24 14:05:23,309 [DEBUG] - Executing command ['C:\ProgramData\chocolatey\tools\7z.exe' x -aoa -bd -bb1 -o"C:\Users\USER\AppData\Local\Temp\chocolatey\chocolatey\musicbee" -y "C:\Users\USER\AppData\Local\Temp\chocolatey\chocolatey\musicbee\MusicBeeSetup_3_0_Update1.zip"]
2016-09-24 14:05:23,354 [ERROR] - ERROR: Exception calling "Start" with "0" argument(s): "Der Verzeichnisname ist ung��g"
2016-09-24 14:05:23,395 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\musicbee\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.
2016-09-24 14:05:23,402 [DEBUG] - Calling command ['"C:\Windows\System32\shutdown.exe" /a']
2016-09-24 14:05:23,428 [DEBUG] - Command ['"C:\Windows\System32\shutdown.exe" /a'] exited with '1116'
2016-09-24 14:05:23,488 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\musicbee'
2016-09-24 14:05:23,491 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\musicbee\musicbee.nupkg'
  with checksum '191FDF5D929082DE11367B1C7525454E'
2016-09-24 14:05:23,495 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\musicbee\musicbee.nuspec'
  with checksum '169C8C3BD6F3C46272D98701C0DDC546'
2016-09-24 14:05:23,498 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\musicbee\tools\chocolateyInstall.ps1'
  with checksum '1A448911A1CF179195D4B14663377F67'
2016-09-24 14:05:23,501 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\musicbee\tools\chocolateyuninstall.ps1'
  with checksum '4621A96AC57D3CCB9DF2DA92C9C731BB'
2016-09-24 14:05:23,503 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\musicbee\tools\musicbeeUninstall.ahk'
  with checksum '38B1A94B6A103871CC5D1BA1C6F46104'
2016-09-24 14:05:23,517 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\musicbee.3.0.5995\.files.update".
2016-09-24 14:05:23,524 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\musicbee.3.0.5995\.sxs".
2016-09-24 14:05:23,527 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\musicbee.3.0.5995\.pin".
2016-09-24 14:05:23,533 [DEBUG] - Attempting to delete directory "C:\ProgramData\chocolatey\lib-bad\musicbee".
2016-09-24 14:05:23,538 [DEBUG] - Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
2016-09-24 14:05:23,542 [ERROR] - The install of musicbee was NOT successful.
2016-09-24 14:05:23,550 [ERROR] - Error while running 'C:\ProgramData\chocolatey\lib\musicbee\tools\chocolateyInstall.ps1'.
 See log for details.
2016-09-24 14:05:23,560 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\musicbee'
 to 'C:\ProgramData\chocolatey\lib-bad\musicbee'
2016-09-24 14:05:25,569 [DEBUG] - Attempting to delete file "C:\Users\USER\AppData\Local\NuGet\Cache\musicbee.3.0.5995.nupkg".
2016-09-24 14:05:25,592 [WARN ] - 
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2016-09-24 14:05:25,608 [INFO ] - 
2016-09-24 14:05:25,619 [ERROR] - Failures
2016-09-24 14:05:25,629 [ERROR] -  - musicbee (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\musicbee\tools\chocolateyInstall.ps1'.
 See log for details.
2016-09-24 14:05:25,641 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2016-09-24 14:05:25,657 [DEBUG] - Exiting with -1
```

I can reprocude this error with there packages:
musicbee
totalcommander
7zip.commandline

I tried replacing 7z.exe and 7z.dell by 64-bit and 32-bit files from the officiall 7zip-setup.
Like suggested here: https://github.com/chocolatey/choco/issues/868#issuecomment-233448770

**Comment by ferventcoder** [comment] 2016-09-24 18:42
Howdy.

When you went to create an issue, did you happen to read the note? 

![image](https://cloud.githubusercontent.com/assets/63502/18810463/8b957250-825c-11e6-923d-fe0842c40acb.png)


This is a duplicate of https://github.com/chocolatey/choco/issues/969

**Comment by ferventcoder** [comment] 2016-09-24 18:43
Big issue though - high priority for a 0.10.2 release.

**Closed by ferventcoder** 2016-09-24 18:42 UTC

**Comment by CWempe** [comment] 2016-09-24 19:28
Sorry for using the wrong repo. :(

Glad the issue is already fixed in the next milestone and I now know hour to work around the issue.
