### ISSUE TITLE
Ability to pass in arguments to the chocolateyinstall.ps1 file

### ISSUE THREAD

**Issue by micahlmartin** [chocolatey/chocolatey#133] opened 2012-07-27 14:31 UTC
I'm using chocolatey to install our custom internal applications. I want the ability to pass in arguments that are accessible to the chocolateyinstall.ps1 file. I could solve some of it by setting some environment variables, but it would be easier if I could pass in the arguments to the installer. Essentially what I'd like to do is this:

`cinst myapp -args @{arg1="value1";arg2="value2"}`

Then from my chocolateyinstall.ps1 file I'd like to access them like this:

```
$args.GetEnumerator() | { 
     #Do something with my arguments
}
```

Currently the `installArguments` is automatically appended to the `exe` or `msi` arguments but I can't parse them or do anything with them from the `chocolateyinstall.ps1` file

Link to original discussion: https://groups.google.com/group/chocolatey/browse_thread/thread/19160bee38885b97?hl=en

**Comment by ferventcoder** [comment] 2015-01-28 05:14
I'm closing this as a dupe of #159 - that's where the work was done. Use -params

**Closed by ferventcoder** 2015-01-28 05:14 UTC

**Comment by alyssenko-ssi** [comment] 2015-10-07 16:56
So did this '$env:chocolateyInstallArguments' functionality ever get implemented? I need to be able to modify the $zabbixConf variable inside the chocolateyInstall.ps1 script for zabbix-agent install- not seeing how this is currently possible?

**Comment by ferventcoder** [comment] 2015-10-08 12:10
@alyssenko-ssi An environment variable for Install Arguments was implemented. However it should not be looked at all for packages. If you need information from the user, one should be using `$env:chocolateyPackageParameters`, see #159.
