### ISSUE TITLE
407 Authentication error through proxy

### ISSUE THREAD

**Issue by ghost** [chocolatey/chocolatey#404] opened 2014-01-20 11:26 UTC
Hello !

When I try to install a package with the command "cinst", I have a proxy authentication error. I could install chocolatey with the command line found here :

https://gist.github.com/erichexter/3717010

And when I do, for example this command "cinst java.jdk", I have this :

```
Chocolatey (v0.9.8.23) is installing 'java.jdk' and dependencies. By installing you accept the license for 'java.jdk' and each dependency you are installing.
______ java.jdk v7.0.51.2 ______
Downloading JDK from http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-windows-x64.exe
Write-Error : Java.JDK did not finish successfully. Boo to the chocolatey gods!
-----------------------
[ERROR] The remote server returned an error: (407) Proxy Authentication Required.
-----------------------
At C:\Chocolatey\chocolateyinstall\helpers\functions\Write-ChocolateyFailure.ps1:30 char:13
+     Write-Error <<<<  $errorMessage
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error
 
Write-Error : Package 'java.jdk v7.0.51.2' did not install successfully: Exception calling "DownloadFile" with "2" argu
ment(s): "The remote server returned an error: (407) Proxy Authentication Required."
At C:\Chocolatey\chocolateyinstall\functions\Chocolatey-NuGet.ps1:90 char:28
+                 Write-Error <<<<  "Package `'$installedPackageName v$installedPackageVersion`' did not install succes
sfully: $($_.Exception.Message)"
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error
 
Finished installing 'java.jdk' and dependencies - if errors not shown in console, none detected. Check log for errors if unsure.
Reading environment variables from registry. Please wait... Done.
```
My environment variables "http.proxy" and "https.proxy" has been setted with my proxy values.

Any idea of how I can solve this ?

Thanks in advance.

Julien.

**Comment by evanw21** [comment] 2015-02-02 07:19
Hi, Another vote for this issue.  The documentation regarding non-AD-integrated Proxies is possibly misleading.  As best I can tell the format that should be used when providing SetEnvironmentVariable values should be something like:
http://DOMAIN\USERNAME:PASSWORD@PROXYSERVER:PROXYPORT if it is to work with nuget
http://docs.nuget.org/consume/nuget-config-settings

This isn't observed outside of nuget
https://github.com/chocolatey/chocolatey/blob/master/src/helpers/functions/Get-WebFile.ps1

Maybe something can be learnt from the nuget implementation?
http://nuget.codeplex.com/SourceControl/latest#src/Core/Http/ProxyCache.cs

**Comment by evanw21** [comment] 2015-02-03 00:00
Further to this, if chocolate/nuget can detect the EnvironmentVariable for proxy settings, can this not equally be observed in the Download-File function of https://chocolatey.org/install.ps1?  This may simplify the install instructions?

**Comment by ferventcoder** [comment] 2015-02-03 03:09
@evanw21 many times is the problem is getting the install.ps1 downloaded in the first place... then everything after that as well.

**Comment by youRFate** [comment] 2015-05-28 12:06
This problem persists with v0.9.9.6.

I've installed chocolatey by manually downloading it and running the installer in powershell. When I tried installing a package it asked me for the credentials, and it also verified them. Providing false credentials resulted in an error. But even with correct crendentials provided, it still fails with `(407) Proxy Authentication Required.`.

**Comment by ferventcoder** [comment] 2015-05-28 14:35
@youRFate I think your issue is related, but not exactly the same as the original discussion. Please follow this issue so you know when it is corrected - https://github.com/chocolatey/choco/issues/243

Thanks!

**Comment by ferventcoder** [comment] 2015-05-28 14:36
~~I think your issue is related, but not exactly the same as the original discussion.~~ (Update, I reread and this is the same).

**Comment by ferventcoder** [comment] 2015-05-28 14:38
Closing this issue as it has moved to choco

**Closed by ferventcoder** 2015-05-28 14:38 UTC
Labels: 0 - Backlog, MoveToChoco

**Comment by youRFate** [comment] 2015-05-28 14:40
@ferventcoder seems like it's the same issue as this one. The proxy is configured in IE as per default company policy, and I also have it set in http_proxy and https_proxy environment vairables.

**Comment by ferventcoder** [comment] 2015-05-28 14:50
I would subscribe to that issue so that you receive notifications on it. Thanks!

**Comment by youRFate** [comment] 2015-05-28 14:54
Already done, I posted some more information over there.

**Comment by ferventcoder** [comment] 2015-05-28 14:54
:)
