### ISSUE TITLE
Chocolatey install not reporting error from bad package

### ISSUE THREAD

**Issue by tyrken** [chocolatey/chocolatey#663] opened 2015-01-20 13:29 UTC
I (intentionally, to test the chef chocolatey cookbook) introduced an error into the chocolateyInstall.ps1 of a new package I'm writing (the filename is wrong), but it is still being reported to install correctly.  It reports a bit of an error but the final messages seem to have forgotten this & report success.

Running on Windows 2008 R2, powershell v2

~~~~
try {
  $packageName = "logrotatewin"
  $url = $(Split-Path -parent $MyInvocation.MyCommand.Definition) + "\..\data\logrotateSetup_utterly_incorrect.msi"

  Install-ChocolateyPackage $packageName "msi" "/quiet" $url

  Write-ChocolateySuccess $packageName
} catch {
  Write-ChocolateyFailure $packageName $($_.Exception.Message)
  throw
}
~~~~

**Comment by ferventcoder** [comment] 2015-01-20 14:36
Duplicate of https://github.com/chocolatey/chocolatey/issues/568

**Comment by ferventcoder** [comment] 2015-01-20 14:36
#658 implements a fix for that.

**Closed by ferventcoder** 2015-01-20 14:36 UTC
Labels: Duplicate Issue
